const wordpress = require('@wordpress/eslint-plugin');

module.exports = [
	{
		ignores: [
			'node_modules/**',
			'vendor/**',
			'build/**',
			'dist/**',
			'scratch/**',
			'scripts/**',
			'**/*.d.ts',
		],
	},
	...wordpress.configs.recommended,
	{
		files: ['**/*.{js,jsx,ts,tsx}'],
		languageOptions: {
			globals: {
				wp: 'readonly',
				RoiFenEditor: 'readonly',
				RoiPgnEditor: 'readonly',
				EgBoardCore: 'readonly',
				Chess: 'readonly',
				console: 'readonly',
				document: 'readonly',
				window: 'readonly',
				clearInterval: 'readonly',
				setInterval: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				fetch: 'readonly',
				parseInt: 'readonly',
				isNaN: 'readonly',
				jQuery: 'readonly',
				confirm: 'readonly',
				alert: 'readonly',
				process: 'readonly',
				roi_course_builder_data: 'readonly',
			},
		},
		rules: {
			'prettier/prettier': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-returns-type': 'off',
			'jsdoc/check-param-names': 'off',
			'jsx-a11y/no-static-element-interactions': 'off',
			'jsx-a11y/click-events-have-key-events': 'off',
			'jsx-a11y/role-supports-aria-props': 'off',
			'jsx-a11y/mouse-events-have-key-events': 'off',
			'jsx-a11y/control-has-associated-label': 'off',
			'jsx-a11y/anchor-is-valid': 'off',
			'jsx-a11y/aria-role': 'off',
			'jsx-a11y/label-has-associated-control': 'off',
			'jsx-a11y/no-autofocus': 'off',
			curly: 'off',
			'no-nested-ternary': 'off',
			'no-lonely-if': 'off',
			'@wordpress/no-unused-vars-before-return': 'off',
			no_unused_vars: 'off',
			'no-shadow': 'off',
			'prefer-const': 'warn',
			'no-console': ['warn', { allow: ['warn', 'error'] }],
			'no-unused-vars': [
				'warn',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
				},
			],
			eqeqeq: 'warn',
			'import/no-unresolved': 'off',
			'import/no-extraneous-dependencies': 'off',
			'no-alert': 'off',
			camelcase: 'off',
		},
	},
];
